apiVersion: v1
kind: Secret
metadata:
  name: rotating-secret
type: Opaque
stringData:
#  api-key: initial-key-v1
#  db-password: initial-pass-v1
  api-key: rotated-key-v2
  db-password: rotated-pass-v2