apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - name: backend
      image: busybox:1.37
      args: ["/bin/sh", "-c", "while true; do echo -e 'HTTP/1.1 200 OK\r\n\r\nhello-from-backend' | nc -l -p 8080; done"]
      ports:
        - containerPort: 8080