apiVersion: v1
kind: Service
metadata:
  name: hello-headless
  namespace: lab-svc
spec:
  clusterIP: None  # This makes it headless
  selector:
    app: hello
    tier: backend
  ports:
  - port: 5678
    targetPort: 5678