apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: svc-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      tier: frontend
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.30
          ports:
            - containerPort: 80