apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-drill
  namespace: lab-deploy
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: rolling-update
          image: nginx:1.29
          ports:
            - containerPort: 80