apiVersion: v1
kind: Pod
metadata:
  name: fail-pod
spec:
  restartPolicy: Never
  containers:
    - name: fail
      image: busybox:1.37
      args: ["/bin/sh", "-c", "echo 'Oops' >&2; exit 1"]
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"