apiVersion: v1
kind: Pod
metadata:
  name: succes-pod
spec:
  restartPolicy: Never
  containers:
    - name: succes
      image: busybox:1.37
      args: ["/bin/sh", "-c", "echo 'All good'; exit 0"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"